const alJubailDEstinationSeedData = [
    {
        id:'2f652add-00f8-4afc-bfb2-3cb27b87f994',
        cityId : '',
        name : 'Al Hamra Park',
        caption : 'Al Hamra Park in Al Jubail is a recreational area for the residents of the neighborhood, covering an area of 75,000 square meters. It includes chairs distributed throughout its extent, a pedestrian path, a bicycle path, as well as a football field and a play area for children, allowing the whole family to enjoy special times amidst greenery and fresh air.',
        description : 'Family outings',
        featureImage : 'https://scth.scene7.com/is/image/scth/al-hamra-park-in-al-jubail-1:crop-1920x1080?defaultImage=al-hamra-park-in-al-jubail-1&wid=1920&hei=1080',
        timing : 'Daily 12:00 AM To 12:00 AM',
        latitude :'26.932168',
        longitude : '49.725813',
    },
    {
        id:'742e72e4-ec1e-458d-9cf7-4f8dea0e2c21',
        cityId : '',
        name : 'Al Nakheel Beach',
        caption : 'Recreational and hiking destination',
        description : 'With its view of the Arabian Gulf coast, Al Nakheel Corniche in Al Jubail is a wonderful tourist destination for beach lovers and walking on the sand, where you can face the successive waves of the sea and enjoy quiet moments in its seating areas designed in the form of a traditional "arish" structure.',
        featureImage : 'https://scth.scene7.com/is/image/scth/al-nakheel-beach-in-al-jubail-1:crop-1920x1080?defaultImage=al-nakheel-beach-in-al-jubail-1&wid=1920&hei=1080',
        timing : 'mon To fri: 9:00 AM To 8:00 PM sat:10:00 AM To 8:00 PM',
        latitude :'27.117934',
        longitude : '49.572265',
    },
    {
        id:'742e72e4-ec1e-458d-9cf7-4f8dea0e2c21',
        cityId : '',
        name : 'Crease Archaeological Tower',
        caption : 'An archaeological landmark carrying a story',
        description :  'Crease Tower is a mud tower that tells the story of glory preserved in the memory of history. It is located in the western part of Al Jubail in the Eastern Region of Saudi Arabia.It was built by order of the founder King Abdulaziz bin Abdulrahman Al Saud in 1928, coinciding with the period of the emergence of the city of Al Jubail at that time.The tower is considered a historical legacy and an important landmark in the region, visited by tourists, antiquities enthusiasts, and history lovers.',
        featureImage : 'https://scth.scene7.com/is/image/scth/crease-archaeological-tower-in-al-jubail-banner-1:crop-1920x1080?defaultImage=crease-archaeological-tower-in-al-jubail-banner-1&wid=1920&hei=1080',
        timing : '',
        latitude :'27.012786',
        longitude : '49.636983',
    },
    {
        id : '',
        cityId : '',
        name : 'Dareen Hills Park',
        caption : 'Large park on the beach',
        description : 'Dareen Hills Park in Al Jubail is characterized by its pleasant atmosphere, refreshing breeze, and stunning nature, covered with vast green spaces overlooking the seaside, making it an ideal daily destination.',
        featureImage : 'https://scth.scene7.com/is/image/scth/dareen-hills-park-in-al-jubail-hero-banner-1:crop-1920x1080?defaultImage=dareen-hills-park-in-al-jubail-hero-banner-1&wid=1920&hei=1080',
        timing: 'Daily 12:00 AM To 12:00 AM',
        latitude: '27.177969',
        longitude : '49.582722',

    },
    {
        id : '',
        cityId : '',
        name : 'The Move Center',
        caption : 'The Splendor of Shopping Near the Sea',
        description : 'Al Jubail is characterized by a modern and different lifestyle that you will feel as soon as you arrive in it, and it is impossible to think of tourism in it without remembering its charming beaches on the Arabian Gulf, which made it a famous summer destination. There are five beaches in Al Jubail Industrial City and two in Al Jubail, and one of its stunning places located on the banks of one of its beaches is The Move Center.',
        featureImage : 'https://scth.scene7.com/is/image/scth/the-move-center-in-jubail-hero-banner-1:crop-1920x1080?defaultImage=the-move-center-in-jubail-hero-banner-1&wid=1920&hei=1080',
        timing: 'Daily 12:00 AM To 12:00 AM',
        latitude: '27.108459',
        longitude : '49.576461',

    },
]
export default alJubailDEstinationSeedData