const hailDestinationSeedData = [

    {
        id: '',
        cityId: '',
        name: 'A Trip to Jabal As Samra',
        caption: 'Between Mountains and History…in Hail',
        description: 'If you are a fan of contemplation and exploring the historical depth of places, then Jabal As Samra in Hail will attract you with its unforgettable stories.',
        featureImage: 'https://scth.scene7.com/is/image/scthacc/jabal-as-samra-in-hail:crop-1920x1080?defaultImage=jabal-as-samra-in-hail&wid=1920&hei=1080',
        timing: '',
        latitude: '27.524523',
        longitude: '41.733198',
    },

    {
        id: '',
        cityId: '',
        name: 'Airef Castle',
        caption: 'A window on the cultural inventory of Hail',
        description: "A'arif Fort stands out with its ancient details and reflects the rich cultural history of the city of Hail. It was built in 1840, and it was named after the mountain on which it was built.",
        featureImage: 'https://scth.scene7.com/is/image/scth/aarif-fort-banner-1:crop-1920x1080?defaultImage=aarif-fort-banner-1&wid=1920&hei=1080',
        timing: 'sat, sun, mon, tue, wed To thu 9:00 AM To 5:00 PM fri:1:00 PM To 6:00 PM',
        latitude: '27.517280',
        longitude: '41.703449',
    },

    {
        id: '',
        cityId: '',
        name: 'Al Adham',
        caption: 'Experience the Magic of Samri Nights and Horse Shows',
        description: 'Visit Al Adham, nestled amidst stunning mountains and a uniquely serene landscape, immerse yourself in the enchanting "Qumra" event, a celebration of Saudi heritage with captivating Samri performances. Held for three nights each Hijri month (14th, 15th, and 16th, excluding Ramadan), this event fills the air with traditional melodies in a vibrant setting under the refreshing evening breeze.',
        featureImage: 'https://scth.scene7.com/is/image/scth/al-adham:crop-1920x1080?defaultImage=al-adham&wid=1920&hei=1080',
        timing: 'Daily 4:00 PM To 1:00 AM',
        latitude: '27.514320',
        longitude: '41.632755',
    },

    {
        id: '',
        cityId: '',
        name: 'Al Mutlaq Heritage Mosque',
        caption: 'A Mosque With 400-Year-Old Stories',
        description: "Al Mutlaq Heritage Mosque has been the subject of the Mutlaq family's care for more than three centuries, passing down the responsibility of its maintenance and restoration from generation to generation. It is one of the oldest and most prominent historical mosques in northern Saudi Arabia, with its foundations rooted in the city of Hail.",
        featureImage: 'https://scth.scene7.com/is/image/scth/almutlaq-heritage-mosque-in-hail-banner-1:crop-1920x1080?defaultImage=almutlaq-heritage-mosque-in-hail-banner-1&wid=1920&hei=1080',
        timing: '',
        latitude: '27.541827',
        longitude: '41.732592',
    },

    {
        id: '',
        cityId: '',
        name: 'Al Qishla Castle',
        caption: 'A Majestic Najdi Heritage in Hail',
        description: 'Discover Al-Qashla Castle in Hail, an iconic heritage site that showcases the traditional Najdi architectural style. Built during the reign of King Abdul Aziz in 1360 AH (1941 CE), Al-Qashla stands as a symbol of Hail’s rich urban heritage. Constructed from clay and stones, the castle features intricate plaster decorations with geometric and floral motifs typical of traditional architecture in the region. Its 12-meter-high cylindrical defensive towers, including four internal "Al-Sandah" towers, emphasize its defensive strength. Within, visitors will find two grand gates, a mosque, and rooms adorned with colorful plaster details and engraved doors and windows, making Al-Qashla Castle a masterpiece of Hail’s architectural legacy.',
        featureImage: 'https://scth.scene7.com/is/image/scth/al-qishla-castle:crop-1920x1080?defaultImage=al-qishla-castle&wid=1920&hei=1080',
        timing: 'sat, sun, mon, tue, wed To thu 9:00 AM To 5:00 PM fri:1:00 PM To 6:00 PM',
        latitude: '27.519132',
        longitude: '41.694320',
    },
     
    {
        id: '',
        cityId: '',
        name: 'Al Samra Mountain',
        caption: 'A Historic Peak with Stunning Views in Hail',
        description: 'Discover Al Samra Mountain, a part of the Shammar Mountains located east of Hail, steeped in history and captivating tales. History reveals that Hatim Al-Tai lit a fire on its summit, known as "Al Mawqida," to guide travelers and passersby to his home. Today, Al Samra Mountain features breathtaking views, a scenic overlook, and an Italian restaurant and cafe offering a unique dining experience. Whether you are exploring its historic legacy or enjoying its serene atmosphere, Al Samra Mountain is a destination that beautifully blends heritage and modern leisure.',
        featureImage: 'https://scth.scene7.com/is/image/scth/Al-Samra-Mountain-two:crop-1920x1080?defaultImage=Al-Samra-Mountain-two&wid=1920&hei=1080',
        timing: 'sun,To thu 9:00 AM To 11:00 PM fri To Sat: 2:00 PM To 11:00 PM',
        latitude: '27.523495',
        longitude: '41.730795',
    },

    {
        id: '',
        cityId: '',
        name: 'Barzan Palace',
        caption: 'Hail’s Iconic Heritage Towers Standing Tall',
        description: "Discover Barzan Palace in the heart of Hail, a historic landmark and one of the region's most important urban heritage sites. Built with towering architecture that once rose above the city’s buildings, Barzan Palace’s two remaining towers—one to the north and another to the south—reach approximately 12 meters high. Named Barzan because it stood prominent among the city’s structures, the palace is now a celebrated tourist attraction, inviting visitors to experience its architectural legacy and significance within Hail's heritage landscape.",
        featureImage: 'https://scth.scene7.com/is/image/scth/barzan-palace-banner:crop-1920x1080?defaultImage=barzan-palace-banner&wid=1920&hei=1080',
        timing: 'sat, sun, mon, tue, wed To thu 9:00 AM To 5:00 PM fri:1:00 PM To 6:00 PM',
        latitude: '27.524281',
        longitude: '41.706224',
    },

    {
        id: '',
        cityId: '',
        name: 'Earth Cafe',
        caption: 'A Cultural Gem in a Mud House',
        description: 'Enjoy your coffee at Earth Cafe, a remarkable breakfast and coffee spot led by a Saudi chef. Located in a traditional mud house, the cafe combines cultural heritage with the warm hospitality of Hail locals. Once a family home, siblings transformed this space into a charming destination that welcomes visitors with its mesmerizing cultural and historical ambiance.Nearby, the family’s old house is also open to visitors, offering a deeper glimpse into their rich heritage and history. Whether you’re looking a delightful breakfast or exploring the authentic surroundings, Earth Cafe provides an unforgettable cultural experience.',
        featureImage: 'https://scth.scene7.com/is/image/scth/earth-cafe:crop-1920x1080?defaultImage=earth-cafe&wid=1920&hei=1080',
        timing: 'Daily 5:00 PM To 2:00 AM',
        latitude: '27.516006',
        longitude: '41.597746',
    },

    {
        id: '',
        cityId: '',
        name: 'Faid Historic City',
        caption: 'Road capital',
        description: 'Historians describe Faid Historic City as the third most important ancient city after Kufa and Basra, as it was located along the ancient Iraqi pilgrimage route known as Zubaida Trail, which connected Iraq with Makkah. The city is located in southeast Hail, 120 km away from it.',
        featureImage: 'https://scth.scene7.com/is/image/scth/historical-fayd-city:crop-1920x1080?defaultImage=historical-fayd-city&wid=1920&hei=1080',
        timing: 'sat, sun, mon, tue, wed To thu 9:00 AM To 5:00 PM fri:1:00 PM To 6:00 PM',
        latitude: '27.113886',
        longitude: '42.526928',
    },

    {
        id: '',
        cityId: '',
        name: 'Hatem Al Ta’ai Palace',
        caption: 'Turan Village: The Legacy of Generosity and History of Hatim Al-Ta’i',
        description: "Discover Turan Village, located 55 kilometers from Hail. Known as the land of the legendary Arab figure Hatim Al-Ta’i, Turan celebrates the enduring legacy of his unmatched generosity, immortalized in Arab culture with the phrase, 'More generous than Hatim. Today, the village preserves remnants of its storied past, including a fortress near the entrance believed to have been Hatim's palace. In the village center, visitors can explore the ruins of an ancient mud palace and a small cemetery with two unusually long graves—one of which, stretching 9.5 meters, is believed by locals to be the resting place of Hatim Al-Ta’i, while the other is thought to belong to his daughter, who is said to have witnessed the dawn of Islam.",
        featureImage: 'https://scth.scene7.com/is/image/scth/hatem-altaai-palace-banner:crop-1920x1080?defaultImage=hatem-altaai-palace-banner&wid=1920&hei=1080',
        timing: 'Daily 12:00 AM To 12:00 AM',
        latitude: '27.586291',
        longitude: '41.444384',
    },

    {
        id: '',
        cityId: '',
        name: 'Umm Sinman',
        caption: 'Ancient Rock Art and Inscriptions in Jubbah',
        description: "Journey through time at Umm Sinman, a UNESCO World Heritage Site since 2015, and one of Saudi's most prominent rock art locations. Situated in the northern region of the Kingdom, the rock faces of Mount Umm Sinman are adorned with human and animal carvings from various historical eras, with the oldest dating back over 12,000 years to the beginning of the Neolithic era. The site also includes ancient Thamudian inscriptions and early Islamic writings, with some inscriptions dating back to 147 AH. These remarkable carvings offer a glimpse into the cultural richness and deep history of human settlement in Jubbah, capturing the essence of ancient life across millennia.",
        featureImage: 'https://scth.scene7.com/is/image/scth/umm-sinman-stairs:crop-1920x1080?defaultImage=umm-sinman-stairs&wid=1920&hei=1080',
        timing: 'sat, sun, mon, tue, wed To thu 9:00 AM To 5:00 PM fri:1:00 PM To 6:00 PM',
        latitude: '28.029469',
        longitude: '40.918592',
    },
]
export default  hailDestinationSeedData;