const TabukDestinationSeedData =[
    {
        id:'5b23f20e-18d4-40c5-b38c-1dc5060c6503',
        cityId : '8519ffad-01e3-4ebd-ad8e-8cdc7fb4a83e',
        name : 'Prince Fahad Bin Sultan Park',
        caption : 'In the arms of nature',
        description : 'On a sunny day or a cold night in Tabuk, you can lay on the green grass that stretches over an area of 500,000 square meters in Prince Fahad Bin Sultan Park, families and friends gather while enjoying a cup of Saudi coffee flavoured with saffron and cardamom, surrounded by lush trees and fresh air.',
        featureImage : 'https://scth.scene7.com/is/image/scth/prince-fahad-bin-sultan-park-tabuk-banner-1:crop-1920x1080?defaultImage=prince-fahad-bin-sultan-park-tabuk-banner-1&wid=1920&hei=1080',
        timing : 'Daily 12:00 AM To 12:00 AM',
        latitude :'28.466458',
        longitude : '36.521315',
    },
    {
        id:'650dff76-3cac-45ff-af97-1856285388bc',
        cityId : '8519ffad-01e3-4ebd-ad8e-8cdc7fb4a83e',
        name : 'Tabuk Archaeological Castle',
        caption : 'Distinctive moments in a place of an ancient past',
        description : 'Tabuk Province is rich with numerous archaeological sites that reveal the history of the area, allowing us to witness symbols of an ancient past, such as Tabuk Archaeological Castle, which dates back over five centuries and is now one of the most important historical castles and tourist landmarks in the region.',
        featureImage : 'https://scth.scene7.com/is/image/scth/islamic-archaeological-tabuk-castle-banner-1:crop-1920x1080?defaultImage=islamic-archaeological-tabuk-castle-banner-1&wid=1920&hei=1080',
        timing : 'sun To thu: 8:00 AM To 2:00 PM fri To sat: 4:00 PM To 6:00 PM',
        latitude :'28.382859',
        longitude : '36.556653',
    },
    {
        id:'3abb9fef-9d22-452f-abf4-42f12cca8bd7',
        cityId : '8519ffad-01e3-4ebd-ad8e-8cdc7fb4a83e',
        name : 'Tabuk Attraction Mud House',
        caption : "A tourist landmark that conveys details of the region's past.",
        description : "A collection of facilities that contain items that date back to Tabuk's rich past can be found in Tabuk Attraction Mud House, or as it is commonly known, the Mud House Museum, which houses various archaeological details and is one of the most prominent tourist landmarks in Tabuk.",
        featureImage : 'https://scth.scene7.com/is/image/scth/mud-house-museum-in-tabuk-1:crop-1920x1080?defaultImage=mud-house-museum-in-tabuk-1&wid=1920&hei=1080',
        timing : 'Daily 4:00 PM To 11:00 PM',
        latitude :'28.383143',
        longitude : '36.556528',
    },
    {
        id:'6fbea00a-6c8c-48a5-afec-e19fd5c92c55',
        cityId : '8519ffad-01e3-4ebd-ad8e-8cdc7fb4a83e',
        name : 'Al-Tawbah Mosque',
        caption : "An Islamic landmark with a building that mimics the Prophet's Mosque",
        description : 'Al-Tawbah Mosque in Tabuk represents an important Islamic landmark as the site where it was built is connected to events from the Battle of Tabuk. The mosque serves as a vital point in the region, around which the markets and neighbourhoods of Tabuk are clustered.',
        featureImage : 'https://scth.scene7.com/is/image/scth/masjid-altawbah-in-tabuk-1:crop-1920x1080?defaultImage=masjid-altawbah-in-tabuk-1&wid=1920&hei=1080',
        timing : 'Daily 12:00 AM To 12:00 AM',
        latitude :'28.384220',
        longitude : '36.558138',
    },
    {
        id:'90fc86d2-88c9-4d9e-b24e-48d573edd418',
        cityId : '8519ffad-01e3-4ebd-ad8e-8cdc7fb4a83e',
        name : 'Tabuk Station in Hejaz Railway',
        caption : 'Evidence of a Unique Islamic Success',
        description : 'Spanning across both distance and time, the Hejaz Railway was established at the beginning of the twentieth century to connect Damascus and Madina in a journey that took no more than five days, compared to the previous 45 days that were required, which involved crossing barren deserts and rugged terrain.',
        featureImage : 'https://scth.scene7.com/is/image/scth/tabuk-station-in-al-hijaz-railway-banner-1:crop-1920x1080?defaultImage=tabuk-station-in-al-hijaz-railway-banner-1&wid=1920&hei=1080',
        timing : 'sun To thu: 8:00 AM To 2:00 PM fri To sat: 4:00 PM To 6:00 PM',
        latitude :'28.387703',
        longitude : '36.561771',
    },

]
export default TabukDestinationSeedData