const YanbuDestinationSeedData = [
    {
        id:'b16d2c5c-8994-4b6d-8887-b91d70e7798b',
        cityId : '7519ffad-01e3-4ebd-ad8e-8cdc7fb4a83e',
        name : 'Al Sumayri Public Park',
        caption : 'One of the must-visit parks in Yanbu',
        description : 'If you want to go for a walk in the fresh air, meditation nd relaxation, or if you want to have fun with your children, Al Sumayri Public Park is your destination.',
        featureImage : 'https://scth.scene7.com/is/image/scth/al-sumayri-public-park-banner-1:crop-1920x1080?defaultImage=al-sumayri-public-park-banner-1&wid=1920&hei=1080',
        timing : 'Daily 4:00 PM To 11:00 PM',
        latitude :'24.013063',
        longitude : '38.214258',
    },
    {
        id:'c7450601-23dd-468d-9618-4d7d1174c52b',
        cityId : '7519ffad-01e3-4ebd-ad8e-8cdc7fb4a83e',
        name : 'Radwa Heritage Museum',
        caption : 'An ancient house turned into a museum',
        description : 'Yanbu has always been a station on the trade route, and the beauty of its beaches has been attracting tourists.',
        featureImage : 'https://scth.scene7.com/is/image/scth/radhwa-museum-in-yanbu-article-1:crop-1920x1080?defaultImage=radhwa-museum-in-yanbu-article-1&wid=1920&hei=1080',
        timing : 'sun To thu:10:00 AM To 10:00 PM fri:3:30 PM To 12:00 AM',
        latitude :'24.080739',
        longitude : '38.061248',
    },
    {
        id:'06bfff75-c8c1-4620-be19-8d118a0467be',
        cityId : '7519ffad-01e3-4ebd-ad8e-8cdc7fb4a83e',
        name : 'Yanbu Historic District',
        caption : 'the charm of the past and authenticity of the present',
        description : 'Heritage monuments remain in Yanbu Historic District, which witnessed many civilizations, peoples, tribes and tumultuous historical events. The monuments are estimated to be about 2500 years old. ',
        featureImage : 'https://scth.scene7.com/is/image/scth/yanbu-historic-gate-1:crop-1920x1080?defaultImage=yanbu-historic-gate-1&wid=1920&hei=1080',
        timing : '',
        latitude :'24.079868',
        longitude : '38.059713',
    },
    {
        id:'a02733f0-2137-4148-a970-629f04e65cd0',
        cityId : '7519ffad-01e3-4ebd-ad8e-8cdc7fb4a83e',
        name : 'Al-Sayegh House of the Arts',
        caption : 'A Gate to a World of Art, Creativity, and Beauty',
        description : 'An outlet for artists, Al-Sayegh House of the Arts is an exceptional destination located in the historical region of Yanbu.  It is a house with a traditional trait in its architecture inspired by the coastal nature of the city.  It includes fine arts that take you to an atmosphere full of amazement without restraining you. On the contrary, it allows your imagination to go wild and is a tourist destination for amateur artists and art lovers. ',
        featureImage : 'https://scth.scene7.com/is/image/scth/alsaaegh-atelier:crop-1920x1080?defaultImage=alsaaegh-atelier&wid=1920&hei=1080',
        timing : 'Daily 5:00 PM To 11:00 PM',
        latitude :'',
        longitude : '',
    },
    {
        id:'c78cf9f4-10f0-4958-9bf7-3a84f6997066',
        cityId : '7519ffad-01e3-4ebd-ad8e-8cdc7fb4a83e',
        name : 'Yanbu Lake Park',
        caption : 'Enjoy the beauty of nature and birds',
        description : 'On your visit to Yanbu, you must go to Yanbu Man-Made Lake (Yanbu Lake Park). It is one of the most beautiful public places in Yanbu, where you can enjoy picturesque nature and take a walk in the open air.',
        featureImage : 'https://scth.scene7.com/is/image/scth/yanbu-lake-park-1:crop-1920x1080?defaultImage=yanbu-lake-park-1&wid=1920&hei=1080',
        timing : '',
        latitude :'24.008353',
        longitude : '38.231153',
    },
]
export default YanbuDestinationSeedData